include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - public_member_api_docs
    - unawaited_futures
    - unnecessary_lambdas
